#!/bin/bash

# This script is designed for i3wm users on Kali Linux

# Basic System Utilities
sudo apt install vlc libinput libinput-bin libinput-dev neofetch feh brightnessctl acpi htop vim figlet toilet build-essential net-tools openvpn -y

# Optional Tools
sudo apt install curl wget guake goldendict youtubedl-gui git tor transmission samba onionshare proxychains cheese vsftpd ufw -y

# Tor Browser Installation
sudo apt install torbrowser-launcher -y

# Brave Browser Installation
sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser -y

# Touchpad Configuration
sudo touch /etc/X11/xorg.conf.d/90-touchpad.conf
cat <<EOF | sudo tee -a /etc/X11/xorg.conf.d/90-touchpad.conf
Section "InputClass"
	Identifier "touchpad"
	MatchIsTouchpad "on"
	Driver "libinput"
	Option "Tapping" "on"
	Option "NaturalScrolling" "on"
	Option "ScrollMethod" "twofinger"
	Option "TappingButtonMap" "lrm"
EndSection
EOF

# i3wm Configuration
cat <<EOF | tee -a ~/.config/i3/config
# =============================================================================================
# ------------------------------------ CUSTOMIZATIONS ----------------------------------------
# =============================================================================================

# Desktop Background image
# exec_always feh --bg-scale <path to image file>

# Shutdown options
mode "exit: [l]ogout, [r]eboot, [s]hutdown" {
  bindsym l exec i3-msg exit
  bindsym r exec systemctl reboot
  bindsym s exec systemctl poweroff
  bindsym Escape mode "default"
  bindsym Return mode "default"
}
bindsym Mod+x mode "exit: [l]ogout, [r]eboot, [s]hutdown"
bindsym Mod+Shift+m exec display-s
bindsym Mod+Shift+p exec display-r
bindsym Mod+Shift+o exec display-l
EOF

# Update bashrc and zshrc to run neofetch on startup
echo 'neofetch' | tee -a ~/.bashrc ~/.zshrc

# Install xrandr for Display Configuration
sudo apt-get update
sudo apt-get install x11-xserver-utils -y

# Display Configuration Scripts
cat <<EOF | sudo tee /bin/display-s /bin/display-r /bin/display-l
xrandr --output HDMI-1-1 --auto --same-as eDP-1
xrandr --output HDMI-1-1 --auto --right-of eDP-1
xrandr --output HDMI-1-1 --auto --left-of eDP-1
EOF
sudo chmod +x /bin/display-s /bin/display-r /bin/display-l
